### ISSUE TITLE
我在Fetching RecordId这步卡住了

### ISSUE THREAD

**Issue by CAFESTU** [rehiy/dnspod-shell#113]
我修改后如下:
```
#!/bin/sh
#

# Import ardnspod functions
. /etc/storage/ardnspod

# Combine your token ID and token together as follows
arToken="8065f04e3f25e81263eca82e6786831b"

# Web endpoint to be used for querying the public IPv6 address
# Set this to override the default url provided by ardnspod
# arIp6QueryUrl="https://6.ipw.cn"

# Return code when the last record IP is same as current host IP
# Set this to a value other than 0 to distinguish with a successful ddns update
# arErrCodeUnchanged=0

# Place each domain you want to check as follows
# you can have multiple arDdnsCheck blocks

# IPv4:
arDdnsCheck "dengpeng.xyz" "www"
```
运行后得到结果
```
R4A:/etc/storage # ./ddnspod.sh
=== Check www.dengpeng.xyz ===
Fetching Host Ip
> Host Ip: Auto
> Record Type: A
Fetching RecordId
> arDdnsLookup -
```

**Comment by Vigilans** [comment]
执行环境是否是使用Busybox的wget（使用`wget --help`查看）？

前段时间这里向`wget`这里加的一行"-4"参数：
https://github.com/rehiy/dnspod-shell/pull/111/files#diff-b9e95544319203cd4295d11dbb63f18712514497bfbfdddca4b8919e0e1399adR117

Busybox版的似乎没有。我发现问题后忘了及时PR上来了。

**Comment by Vigilans** [comment]
新的Commit添加上去了，再测试一下是否可用？

**Comment by withero** [comment]
你好，遇到同样的问题，BusyBox版本如下 ，用6.2 2022-11-15的还是不行。
BusyBox v1.24.2 (2022-02-18 10:40:10 UTC) multi-call binary.

**Comment by Vigilans** [comment]
经过测试，BusyBox直到v1.25.1以前，不支持`--no-check-certificate`参数。（这也意味着即使在https://github.com/rehiy/dnspod-shell/pull/111/files#diff-b9e95544319203cd4295d11dbb63f18712514497bfbfdddca4b8919e0e1399adR117 的改动之前，在v1.25.1版本以下的BusyBox执行脚本也是会失败的）。

我会再细化一下BusyBox的版本检查逻辑发上来。

**Comment by withero** [comment]
收到，感谢，更新后第一时间测试。另我是在Padavan路由器固件里使用的。

**Comment by Vigilans** [comment]
> 收到，感谢，更新后第一时间测试。另我是在Padavan路由器固件里使用的。

@withero 刚刚测试那些没有`--no-check-certificate`选项的似乎都不支持HTTPS访问，所以可以先试下`wget -O- https://baidu.com`能不能使用？

如果上面`https://baidu.com`访问没问题的话，试下直接使用下面命令：
```
wget -q  -O- --no-check-certificate -U "AnripDdns/6.2.0(wang@rehiy.com)" --post-data "login_token=<你的arToken>&format=json&lang=en" https://dnsapi.cn/Info.Version
```
看看wget会不会有报错？

如果服务器正常返回了一个JSON（版本信息），可以再使用下面的命令：
```
wget -q  -O- --no-check-certificate -U "AnripDdns/6.2.0(wang@rehiy.com)" --post-data "login_token=<你的arToken>&format=json&lang=en&domain=<你的域名>&sub_domain=<你的子域名>&record_type=A" https://dnsapi.cn/Record.List
```
看看是否能获取`Operation Successful`的JSON，如果能获取代表`Fetching RecordId`是成功的，没有的话再继续定位下问题。

**Comment by withero** [comment]
连接百度正常，
wget第1条返回结果应该也是正常的：{"status":{"code":"1","message":"4.6","created_at":"2022-11-22 22:08:08"}}
wget第2条返回结果：{"status":{"code":"10","message":"No records on the list","created_at":"2022-11-22 22:11:20"}}

**Comment by Vigilans** [comment]
> 刚又试了下，之前子域名解释在CNAME上的，所以没成功，换到A记录就正常了。看到了Operation Successful记录

修改到A记录后，`ddnspod.sh`是否能正常使用了？

> 因为这个状况脚本里不知道能不能自动禁用CNAME换成启用或新增A记录。

@withero 这个可以参考作者在https://github.com/rehiy/dnspod-shell/issues/94 里的回复：
>> Q: 现在我要解析一个新的域名，必须先去dnspod建一个才能用这个解析，能不能一步到位？
>
>> A: 这样的操作有些越权

---

不知你的CNAME使用场景如何，我个人也是在使用CNAME记录的，我的理解和设计思路是：
* A/AAAA记录的域名应尽可能详细地描述这个IP的特征，并通过DDNS更新；
* CNAME记录作为“引用”或“别名”，用来指向一个具体的A/AAAA记录，或是套娃另一个CNAME记录，从而简化域名/表示一个解析策略。

按照以上理解，CNAME记录应该是在dnspod里一开始就静态写好的，并且不应被用于DDNS，从而只要网络拓扑没有改变，没有更新的必要。

举例：某域名为`test.domain`，然后在上海有一个同时接入了三大运营商宽带的路由器（并在如杭州等城市也有自己管理的路由器设备），可以这样设计域名：
* 上海电信路由器（A/AAAA）：`sh.telecom.router.test.domain`
* 上海联通路由器（A/AAAA）：`sh.unicom.router.test.domain`
* 上海移动路由器（A/AAAA）：`sh.cmcc.router.test.domain`
* 电信路由器（CNAME，以上海为主节点）：`telecom.router.test.domain` -> `sh.telecom.test.domain`
* 上海路由器（CNAME，以电信为主出口）：`sh.router.test.domain` -> `sh.telecom.test.domain`
* 路由器（CNAME，以上海为主节点）：`router.test.domain` -> `sh.router.test.domain`

**Comment by withero** [comment]
修改为A记录也不行。
但是使用6.1分支功能全正常了。
6.2的不行。

**Comment by Vigilans** [comment]
@withero 试着使用一下 https://github.com/Vigilans/dnspod-shell/blob/vigilans/debug-%23113/ardnspod 里更新的脚本，把输出日志贴到issue里看看？

我在Fetching RecordId相关的每一步添加了debug输出，这样来定位一下你那一边具体的报错_(:з」∠)_

**Comment by Vigilans** [comment]
> arDdnsApi - calling curl
> arDdnsApi - dnsapi output:

所以你的路由器有`curl`，并且v6.2脚本优先调用了`curl`，且没有任何输出。

而v6.1分支里是优先调用wget的：
https://github.com/rehiy/dnspod-shell/blob/404b48f5468e0e401301f7f23667f39eff417c3e/ardnspod#L119-L123
因此对应上面我们对`wget`作的没问题的测试，能够正常使用。

所以再直接测试一下下面的命令？
```
curl -4 -s -A "AnripDdns/6.2.0(wang@rehiy.com)" -d "login_token=<你的arToken>&format=json&lang=en&domain=<你的域名>&sub_domain=<你的子域名>&record_type=A"  https://dnsapi.cn/Record.List
```
如果像上面日志一样没有任何输出的话，加个`-v`试试：
```
curl -v -4 -s -A "AnripDdns/6.2.0(wang@rehiy.com)" -d "login_token=<你的arToken>&format=json&lang=en&domain=<你的域名>&sub_domain=<你的子域名>&record_type=A"  https://dnsapi.cn/Record.List
```

**Comment by withero** [comment]
-s没反应，加-v如下：

* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by Vigilans** [comment]
@withero 所以应该是padavan路由器里缺少了ca-certificates导致的……`wget`里用了`--no-check-certificate`，所以不会校验证书，没有ca-certificates也没事。

试着加上`-k`选项？
```
curl -v -4 -k -A "AnripDdns/6.2.0(wang@rehiy.com)" -d "login_token=<你的arToken>&format=json&lang=en&domain=<你的域名>&sub_domain=<你的子域名>&record_type=A"  https://dnsapi.cn/Record.List
```

以及在上面wget命令里去掉`--no-check-certificate`选项，估计会有类似的报错。

**Comment by Vigilans** [comment]
我打算在`dnspod-shell`里curl对应位置加入`-k`参数来与wget的`--no-check-certificate`选项对应，这样可以修复`dnspod-shell`在你的机器上的工作。

@withero 如果你打算修curl在你的padavan固件上的问题，可以参考下这个帖子 https://serverfault.com/questions/485597/default-ca-cert-bundle-location ，试着找一下curl尝试使用了哪里的证书文件。有两种似乎可行的方案：
* `curl -v https://baidu.com`, curl可能会打印`CAfile`的位置，我这边是：
```
# curl -v https://www.baidu.com
*   Trying 36.152.44.95:443...
* Connected to www.baidu.com (36.152.44.95) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
```
* 装一下`strace`，如果路由器上有opkg的话可以用`opkg install strace`安装，然后运行`strace curl https://baidu.com 2>&1 | grep open`，找下其中与ssl有关的文件，例如我这边有：
```
openat(AT_FDCWD, "/usr/lib/libssl.so.1.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/ssl/openssl.cnf", O_RDONLY|O_LARGEFILE) = 3
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY|O_LARGEFILE) = 6
```

**Comment by Vigilans** [comment]
@withero 
BusyBox的wget里没有手动指定参数的选项(`--ca-certificates`)；
一些嵌入式设备里可能没有/etc/ssl/certs；

以上等等因素考虑起来，相比直接取消CA证书检查，写一个适用所有情况的HTTPS网络请求函数要麻烦不少。

不过考虑到不检查CA证书总归是不好的，按你说的尝试手动指定一下证书位置确实还是可以考虑。

**Comment by rehiy** [comment]
已实现curl/wget封装，考虑到老旧设备，默认不检测证书。
应对一些特殊情况，可以在 ddnspod.sh 中 重写 arRequest 方法

**Comment by withero** [comment]
收到。谢谢，已经可以用了，我也在尝试封装自己的Padavan。
