### ISSUE TITLE
能否增加IP相同判断

### ISSUE THREAD

**Issue by ulpyuxa** [rehiy/dnspod-shell#115]
如题：
1. 第一次运行时，直接更新子域名的IP，并保存子域名与本次IP的对应关系到本地文件中
2. 第二次运行时，判断当前路由器的IP是否与保存在本地文件中的子域名IP是否一致，如果一致，则不触发更新，反之则更新，这样可以保证最小频次调用接口。防止dnspod接口被禁

**Comment by rehiy** [comment]
可以参考下5.0分支。出于请求次数越少越稳定的，新版使用了dnspod的新ddns接口。是否更新交由dnspod服务端判断。

**Comment by ulpyuxa** [comment]
我觉得缓存文件会保险一点，可能后面平台又出什么政策，那就over了。

**Comment by Vigilans** [comment]
现在arDdnsCheck会向stdout里写入目前dnspod上的最新地址，并返回一个代码表示更新状态。此外，`ddnspod.sh`里增加了一个新配置项`arErrCodeUnchanged`，用于dnspod上的就是最新IP，无需更新时的返回代码（默认为0，可以修改为非0用于提取这个信息）。

因此通过这些信息的组合，是可以通过自定义一下`ddnspod.sh`，实现你的需求的（如取出stdout结果自己保存一下就行）。

**Comment by ulpyuxa** [comment]
Nice...
