### ISSUE TITLE
脚本更新公网ipv6地址总是选择到临时地址怎么办

### ISSUE THREAD

**Issue by ggtony233** [rehiy/dnspod-shell#117]
如题，ipv6公网地址有两个，现在脚本一直选择临时ipv6地址做为更新对象，应当如何修改呢？

**Comment by Vigilans** [comment]
请参考https://github.com/rehiy/dnspod-shell/pull/112, 为`arDdnsCheck`提供了第四个参数`接口名`，选择指定接口上的IP地址，并偏向于选择固定地址（也即非临时ipv6地址）。

目前参数下，脚本的行为是选择用于上网的出口地址（也即用于发送网络请求的IP地址），因此在这种行为下脚本是否选择临时地址是由操作系统所控制的。Linux下，可以通过`net.ipv6.conf.*.use_tempaddr`内核设置来控制临时地址的行为。

因此你可以：
1. 保持脚本不变，修改内核设置，使用非临时地址作为上网地址（但是也失去了临时地址保护隐私的意义，非临时地址更多是作为服务器供他人访问的）。
2. 使用PR #112 里面提供的更新后的脚本。如果觉得该解决方案不错可以留言支持该PR合并进主线。

**Comment by ggtony233** [comment]
> 请参考#112， 为提供了第四个参数，选择指定接口上的IP地址，并偏向于选择固定地址（也即非临时ipv6地址）。`arDdnsCheck``接口名`
> 
> 目前参数下，脚本的行为是选择用于上网的出口地址（也即用于发送网络请求的IP地址），因此在这种行为下脚本是否选择临时地址是由操作系统所控制的。Linux下，可以通过内核设置来控制临时地址的行为。`net.ipv6.conf.*.use_tempaddr`
> 
> 因此你可以：
> 
> 1. 保持脚本不变，修改内核设置，使用非临时地址作为上网地址（但是也失去了临时地址保护隐私的意义，非临时地址更多是作为服务器供他人访问的）。
> 2. 使用公关[实现对从特定接口检索主机 ip 的支持#112](https://github.com/rehiy/dnspod-shell/pull/112) 里面提供的更新后的脚本。如果觉得该解决方案不错，可以留言支持该PR合并进主线。

有个问题，这个版本直接执行是可以的，但我在cron 中无法正确的执行他

**Comment by ggtony233** [comment]
在cron中#112貌似无法正确的执行
