### ISSUE TITLE
关于使用Go适配api3.0

### ISSUE THREAD

**Issue by rehiy** [rehiy/dnspod-shell#123]
目前官方api已进入维护期，将逐步转为腾讯云api3.0，而新接口无法使用shell进行简单签名计算，或者说依赖很多第三方库。

目前已经和官方团队沟通，开发了go的签名二进制程序。但是打包体积将近4m，大家有什么想法可以说说。

**Comment by Vigilans** [comment]
现在有没有相关文档或原型实现可供参考？

如果是能够通过在`ardnspod`里添加数百行签名计算函数来实现的话，我是觉得可以的，因为我在自己的fork里添加的“根据接口与MAC地址获取局域网设备的IPv6地址”功能就添加了许多的工具代码函数：

https://github.com/Vigilans/dnspod-shell/commit/da4ddd6dd200d1e5df52df372c4cb6baffd60ca6

**Comment by rehiy** [comment]
签名算法可参考我另一个项目源码 https://github.com/tdp-resource/tencent-cloud-api-cli/blob/bare/tencentcloudapi_curl.go

**Comment by lanlandexiaolan** [comment]
4M还好，希望可以在busybox里跑

**Comment by c4yg70** [comment]
我觉得提前跟随官方 api 版本对终端进一步实现比较友好，包括从 dnspod token 迁移到 腾讯云 api token

**Comment by himao** [comment]
官方旧版API未停止服务的话，希望能保持shell版的可用性。主要在路由器里运行，go版略大了些，可能还有交叉编译适配问题，兼容性应该不如shell版。
官方API升级更多的是产品整体规划调整，就本项目的核心功能来说，跟随升级的必要性不大。

**Comment by rehiy** [comment]
和官方沟通过这个问题了，短期内旧版接口不会下线。另外Go版本基本是可以覆盖全平台的，唯一的缺点就是体积大。

**Comment by c4yg70** [comment]
> 和官方沟通过这个问题，短期内旧版接口不会下线。另外Go版本基本是可以覆盖全平台的，唯一的缺点就是体积大。

旧接口使用的是 dnspod api，新接口可以兼容对 腾讯云 RAM api权限，对权限管理友好一些。

体积问题可以把新旧程序拆分成两个项目（哈哈

**Comment by rehiy** [comment]
shell 算法，我已实现 https://www.rehiy.com/post/534/。新版本开发也将列入日程。
