### ISSUE TITLE
ardnspod代码里边的小问题

### ISSUE THREAD

**Issue by fangjzh** [rehiy/dnspod-shell#124]
在ardnspod文件的[第327行](https://github.com/rehiy/dnspod-shell/blob/6d37d801f5d4b4b832599bde8fe3fe9cf3e6c56e/ardnspod#L327)     
`elif [ "$recordIp" = "$lastRecordIp" ]; then`
‘=’应该是‘==’ ？

**Comment by Vigilans** [comment]
https://stackoverflow.com/questions/20449543/shell-equality-operators-eq

== 与 [[ ]] 是bash支持的语法，而ardnspod需要在仅支持POSIX shell的环境上运行。

**Comment by fangjzh** [comment]
受教，谢谢！
