### ISSUE TITLE
能否加入支持同一域名对应多个线路的支持？

### ISSUE THREAD

**Issue by bluehj777** [rehiy/dnspod-shell#125]
目前好像只是能更改一个域名的默认记录。如果该域名在电信线路，联通线路上有更多记录，怎不支持了

**Comment by Vigilans** [comment]
可以用CNAME记录定义这个设计：
dnspod-shell运行在三个域名上：
* 电信: tele.domain
* 联通: unic.domain
* 移动: cmcc.domain

dnspod里添加三个记录：
* domain, 电信时: CNAME到tele.domain
* domain, 联通时: CNAME到unic.domain
* domain, 移动时: CNAME到cmcc.domain

**Comment by bluehj777** [comment]
> 可以用CNAME记录定义这个设计： dnspod-shell运行在三个域名上：
> 
> * 电信: tele.domain
> * 联通: unic.domain
> * 移动: cmcc.domain
> 
> dnspod里添加三个记录：
> 
> * domain, 电信时: CNAME到tele.domain
> * domain, 联通时: CNAME到unic.domain
> * domain, 移动时: CNAME到cmcc.domain

嗯嗯，完美解决。真没想到这么套娃:-)
