### ISSUE TITLE
v6.3.0反复更新重复的IP

### ISSUE THREAD

**Issue by genezx** [rehiy/dnspod-shell#126]
2023-03-06 14:35:44(DDNS): (27.19.24.83) 修改 A 记录 默认 线路 dyn.lcz.wh 值 27.19.24.83 为 A 记录 默认 线路 dyn.lcz.wh 值 27.19.24.83 (1263204358) Uin:1145141919810 Real Client IP:27.19.24.83 API FROM:DNSPOD
2023-03-06 14:35:02(DDNS): (27.19.24.83) 修改 A 记录 默认 线路 dyn.lcz.wh 值 27.19.24.83 为 A 记录 默认 线路 dyn.lcz.wh 值 27.19.24.83 (1263204358) Uin:1145141919810 Real Client IP:27.19.24.83 API FROM:DNSPOD

**Comment by rehiy** [comment]
我向官方产品提个iss，是否可以单列ddns记录，且我们也可以尝试使用本地文件做个缓存试试

**Comment by rehiy** [comment]
直接向官方接口查询当前ip，会增加失败率
从dns获取则有延迟
本地文件缓存也增加io读写和权限问题
本地环境变量存储，不能使用计划任务

如果确实对这个日志接受不了，我们可以权衡下

**Comment by rehiy** [comment]
另外，可以看下脚本的arErrCodeUnchanged参数，开启变更检测

**Comment by genezx** [comment]
没错，我就是对这个刷屏日志接受不了，一天时间就能把以前的所有改动记录刷没了。我正在向官方发工单沟通这个问题，如果官方能解决，这边就不需要改动了。

**Comment by rehiy** [comment]
你先看下arErrCodeUnchanged

**Comment by Vigilans** [comment]
> 你先看下arErrCodeUnchanged

目前无论arErrCodeUnchanged是何值，都会调用一次更新API。当arErrCodeUnchanged不为0时，`arDnspod`会先拿一次旧IP，然后进行一次更新，然后再将返回的新IP与旧IP进行比对来输出0（新旧不同）或者$arErrCodeUnchanged（新旧相同）。也就是拿旧IP只起到反馈的作用。

作个折中的话，可以有下面的方案：
1. 只要能拿到`$lastRecordIp`，且获取到了`$hostIp`（`$5`不为0），那么就进行一次本地比对，未改变则不调用更新API。
2. 添加一个配置，用于向指定的路径写入更新后的IP。这个文件最好是`hosts`风格的，以便能被其他的服务使用（如dnsmasq）。当此配置生效时，`ardnspod`会从这个配置中获取`$lastRecordIp`。
3. 当`arErrCodeUnchanged`不为0时，一定需要获取`$lastRecordIp`。若2中所述配置生效，则使用2中获取的`$lastRecordIp`，若未生效，则从官方接口查询`$lastRecordIp`。

**Comment by genezx** [comment]
> 我向官方产品提个iss，是否可以单列ddns记录，且我们也可以尝试使用本地文件做个缓存试试

官方已经回复我说，就这样，没法改，晕了。

**Comment by genezx** [comment]
> 直接向官方接口查询当前ip，会增加失败率 从dns获取则有延迟 本地文件缓存也增加io读写和权限问题 本地环境变量存储，不能使用计划任务
> 
> 如果确实对这个日志接受不了，我们可以权衡下

现在的问题就是，始终调用一次更新API一定会在日志刷屏，为了不刷屏一定要想办法获取上次的IP。当然可以通过配置控制这个行为。

获取上次IP目前有几个办法，各有优缺点，就是你上面提到的：
1. 直接向官方接口查询当前ip，会增加失败率
2. 从dns获取则有延迟
3. 本地文件缓存也增加io读写和权限问题
4. 本地环境变量存储，不能使用计划任务

DDNS也可以分两个场景：
1. 对IP变化极度敏感，不能接受秒级延迟
2. 对IP变化中度敏感，可以接受秒级延迟，不能接受分钟级延迟
3. 对IP变化不太敏感，可以接受分钟级的延迟

对于第一个场景，几乎一定是在计划任务里执行的，我认为可以选择第三种方案。

对于第二个场景，也几乎一定是在计划任务里执行的，我认为选择方案一、三均可，因为失败一两次影响不大。

对于第三个场景，我认为选择方案一、二、三、四均可，既然可以接受分钟级延迟，那么多延迟一两次也能接受。

我认为io读写并不是什么问题，毕竟IP发生变化是小概率事件，多数时候仅仅只是在读取，况且还有/dev/shm这种内存文件系统可以用。权限就更不是问题了。

**Comment by rehiy** [comment]
常规linux的确没问题，很多嵌入式设备，有各种写限制，我之前尝试过，很多反馈用不了。所以之后有一版改为了从dnspod查询当前地址。再之后推动dnspod优化了ddns接口，从此不再需要担心接口请求速率，而对比地址。目前的日志又给大家带来不便，我们尝试更改下，留一个手动开关。

**Comment by bluehj777** [comment]
同样问题。我的AnripDdns是部署在内网，并没有放在出口上，所以是调用https://dnsapi.cn获取外网IP，那么为什么不能先读取DNS的ip，然后和https://dnsapi.cn获取的ip比对下？如果不同再更新记录呢？

**Comment by bluehj777** [comment]
> 3\. 本地文件缓存也增加io读写和权限问题
感觉相对来说，用本地缓存验证一下的方式更通用些

**Comment by bluehj777** [comment]
> 尝试在/run/记录了最后的ip，可以测试下新版。另一个方案是写入到 /tmp，看看大家的反馈后决定哪个作为默认值吧

新版在一般的LINUX发行版下基本没问题。

**Comment by rehiy** [comment]
临时文件目录只要可写，就不是大问题

**Comment by okyaa** [comment]
目前2023/5/24的版本使用/tmp临时目录文件的方案在同时更新IPV4和IPV6 多域名解析的时候会造成校验本地存储的IP和获取的HOSTIP不一致，反复发起IP更新，建议在临时文件中能分别记录。

**Comment by rehiy** [comment]
可以考虑根据子域名和ip类型缓存

**Comment by okyaa** [comment]
是的，但我不会写：），暂时注释了，还直接和dnspod上获取的进行比较。

**Comment by rehiy** [comment]
fixed，可以测试下

**Comment by okyaa** [comment]
测试正常，感谢！
