### ISSUE TITLE
不能解析泛域名

### ISSUE THREAD

**Issue by gaojiannote** [rehiy/dnspod-shell#134]
刚用这个脚本，可以解析域名本身（A记录，用@表示），不能解析泛域名（A记录，用*表示），看脚本也允许成功了，就是dnspod没有更新泛域名A记录值。

**Comment by rehiy** [comment]
要实现泛域名可以cname到一个二级域名解决

**Comment by gaojiannote** [comment]
使用泛域名的方法已经解决了，谢谢您的回复。
