### ISSUE TITLE
增加说明：用一条命令即可执行

### ISSUE THREAD

**Issue by Omoinemie** [rehiy/dnspod-shell#135]
我想创建一个定时任务，定时下载主脚本，命令中附带用户信息，域名信息，指定网卡，用一条命令即可完成解析，这样就不用将文件保存到本地，适用大部分系统。

**Comment by rehiy** [comment]
可以这么用，问题是容易下载不过来

**Comment by Omoinemie** [comment]
http://tx.vomiku.com/app/sh/ardnspod
我的服务器，长期有效的
