### ISSUE TITLE
双WAN的情况，有没有办法同时更新2个网卡的V6域名分别更新？

### ISSUE THREAD

**Issue by Paladin-F** [rehiy/dnspod-shell#141]
目前只能更新第一块网卡上获取到的V6地址。
另外，如果有运营商更新的情况可能获取到的V6地址不正确

**Comment by Vigilans** [comment]
这个功能是支持的：
https://github.com/rehiy/dnspod-shell/pull/112

**Comment by Paladin-F** [comment]
> 这个功能是支持的： #112

测试成功了，多谢！
