### ISSUE TITLE
运行出现Last Ip: arDdnsRecordIp - {"status":{"code":"8","message"无法更新IP

### ISSUE THREAD

**Issue by ken136818346** [rehiy/dnspod-shell#72]
Fetching Host Ip
> Host Ip: 119.129.XX.XX
> Record Type: A
Fetching Ids of XXXXXX.tk
> Domain Ids: 86670461 798518213
Checking Record for XXXXXX.tk
> Last Ip: arDdnsRecordIp - {"status":{"code":"8","message":"\u8bb0\u5f55\u7f16\u53f7\u9519\u8bef","created_at":"2021-04-24 22:04:23"}}
Fetching Host Ip
> Host Ip: 240e:3b4:ce:8360:3408:XXXX:XXXX:d4XX
> Record Type: AAAA
Fetching Ids of XXXXXX.tk
> Domain Ids: 86670461 798518282
Checking Record for XXXXXXXXd.tk
> Last Ip: arDdnsRecordIp - {"status":{"code":"8","message":"\u8bb0\u5f55\u7f16\u53f7\u9519\u8bef","created_at":"2021-04-24 22:04:24"}}

请问是什么问题导致的，应该如何解决？
3Q

**Comment by rehiy** [comment]
"status":{
        "code":"8",
        "message":"记录编号错误",
        "created_at":"2021-04-24 22:04:23"
    }

**Comment by rehiy** [comment]
fixed
