### ISSUE TITLE
ip addr list出现奇怪的vethhole

### ISSUE THREAD

**Issue by qiankanglai** [rehiy/dnspod-shell#74]
最近发现脚本刷的ip非常奇怪, ssh上去看了下`ip -o -4 addr list`发现有多了一条

> 9: vethhole    inet 253.253.253.253/24 brd 253.253.253.255 scope global vethhole\       valid_lft forever preferred_lft forever

我暂时修改了 `grep -Ev '\s(docker|lo|vethhole)'`绕开了,不知有没有遇到过类似情况

**Comment by rehiy** [comment]
脚本已更新
