### ISSUE TITLE
建议用source导入ardnspod

### ISSUE THREAD

**Issue by kooritea** [rehiy/dnspod-shell#78]
有的shell会隔离直接执行声明的方法，使用source就不会有这个问题
```bash
. /your_real_path/ardnspod

source . /your_real_path/ardnspod
```

**Comment by rehiy** [comment]
部分环境下没有 source 指令，只能使用 .
&nbsp;

若海 https://www.rehiy.com


&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2021年5月26日(星期三) 下午3:59
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: [rehiy/dnspod-shell] 建议用source导入ardnspod (#78)





 
有的shell会隔离直接执行声明的方法，使用source就不会有这个问题
 . /your_real_path/ardnspod source . /your_real_path/ardnspod

**Comment by kooritea** [comment]
才知道sh里面没有source。。
