### ISSUE TITLE
ardnspod 6.21 版本无法更新IP记录

### ISSUE THREAD

**Issue by Aerithlon** [rehiy/dnspod-shell#82]
6.20还有之前的版本一直正常，今天更新了6.21的ardnspod文件之后，无法正常更新IP记录，斐讯路由器上运行。

**Comment by rehiy** [comment]
是否有错误信息

**Comment by Aerithlon** [comment]
没有错误提示，就是执行到一半，应该是获取ip那里然后不继续执行了，现在版本退回到6.2.0了，可为什么网站这边退回6.1.1了？6.2.0也有问题吗

**Comment by rehiy** [comment]
我没发布6.20以上版本呀？难道跟其他合并者的版本冲突了？是否可以测试下6.1.1，或者提供您运行的系统类型和版本。

**Comment by Aerithlon** [comment]
测试6.1.1版本没有问题，功能正常

[K3C /opt/dnspod]# ./ddnspod.sh
Fetching Host Ip
> Host Ip: 183.188.100.174
> Record Type: A
Fetching Ids of k3c.#####.com
> Domain Ids: 7####660 7####1683
Checking Record for k3c.#####.com
> Last Ip: 183.188.100.161
Updating Record for k3c.#####.com
> arDdnsUpdate - success

6.2.1执行到 Fetching Ids of k3c.#####.com，然后Domain Ids: 这里就停止了。另外为什么有的版本更新了IP地址以后TTL是10，而有的版本就是600，比如6.1.1就是官方默认的600，而6.2.0更新以后就是10，记得以前的版本也是10。

**Comment by Aerithlon** [comment]
6.2.0和6.2.1版本确实有过，也是从这个页面下载的，6.2.0是6月7日更新的，发布者确实是另一个作者，我电脑里现在还有。

**Comment by rehiy** [comment]
抱歉，这个版本的确有问题。后续有修复提交。

是我把其他合并者的版本号给忽略了，不好意思~~

回归原始问题：现在的的最后版本我测试可以，你这边运行正常么？

**Comment by Aerithlon** [comment]
> 抱歉，这个版本的确有问题。后续有修复提交。
> 
> 是我把其他合并者的版本号给忽略了，不好意思~~
> 
> 回归原始问题：现在的的最后版本我测试可以，你这边运行正常么？

现在版本使用正常，没有问题，更新了ip地址以后TTL保持原有的不做修改。
