### ISSUE TITLE
请问在openwrt上使用此脚本需要加装什么依赖模块吗（目前脚本运行无效）？

### ISSUE THREAD

**Issue by yubanmeiqin9048** [rehiy/dnspod-shell#84]
root@OpenWrt:~# /etc/ddns/ddnspod.sh
Fetching Host Ip
> Host Ip: xxxxxxxxc:1401:d6xxxxxxdbxx1a3f:fb3c:c2xx
> Record Type: AAAA
Fetching Ids of subdomain6.*.example.ax.org
> Domain Ids: arDdnsIds - {"status":{"code":"8","message":"\u57df\u540d\u4e0d\u6b63\u786e\uff0c\u8bf7\u8f93\u5165\u4e3b\u57df\u540d\uff0c\u5982 dnspod.cn","created_at":"2021-08-15 01:29:02"}}

（敏感信息已作处理）

**Comment by rehiy** [comment]
请安装 curl 或 openssl 后试试
