### ISSUE TITLE
padavan问题

### ISSUE THREAD

**Issue by lsx25** [rehiy/dnspod-shell#85]
padavan设置完成后，不能用，提示
Fetching Host Ip
> Host Ip: 111.225.***.54
> Record Type: A
Fetching Ids of www.****.cn
wget: can't execute 'openssl': No such file or directory

padavan需要安装 penssl模块吗？能指导怎么安装吗？

**Comment by rehiy** [comment]
需要安装openssl，具体如何安装请参考社区帖子
