### ISSUE TITLE
脚本似乎失效了?请问这是什么情况

### ISSUE THREAD

**Issue by errors4ever** [rehiy/dnspod-shell#87]
作者你好,这个脚本之前使用了一两个月均无问题,这几周无论是crontab还是手动执行脚本都不更新ip地址了,请问是什么问题呢

**Comment by errors4ever** [comment]
以下为运行信息
Fetching Host Ip
> Host Ip: 61.173.34.31
> Record Type: A
Fetching Ids of subdomain.www.error-forever.com
> Domain Ids: arDdnsIds - {"status":{"code":"8","message":"\u57df\u540d\u4e0d\u6b63\u786e\uff0c\u8bf7\u8f93\u5165\u4e3b\u57df\u540d\uff0c\u5982 dnspod.cn","created_at":"2021-09-06 21:24:15"}}
Fetching Host Ip
> Host Ip: 240e:388:1a01:1100:61f1:7c92:ead1:5c51
> Record Type: AAAA
Fetching Ids of subdomain6.www.error-forever.com
> Domain Ids: arDdnsIds - {"status":{"code":"8","message":"\u57df\u540d\u4e0d\u6b63\u786e\uff0c\u8bf7\u8f93\u5165\u4e3b\u57df\u540d\uff0c\u5982 dnspod.cn","created_at":"2021-09-06 21:24:16"}}

**Comment by errors4ever** [comment]
以下为配置文件
# IPv4:
arDdnsCheck "www.error-forever.com" "subdomain"

# IPv6:
arDdnsCheck "www.error-forever.com" "subdomain6" 6

**Comment by errors4ever** [comment]
上面那串解码出来是"域名不正确，请输入主域名，如 dnspod.cn" 但我的域名是对的呀...

**Comment by rehiy** [comment]
测试未发现问题，你这里好了么？

**Comment by errors4ever** [comment]
没有,dns后台操作日志也没有记录,不知道我这哪里出了问题

**Comment by yulelong** [comment]
我这里也是类似的问题，无法更新IP（我只有一个AAAA记录）

**Comment by yulelong** [comment]
更正：我的域名实际上是XXXX.XX，不是WWW.XXXX.XX，配置文件中，我之前写的是 arDdnsCheck XXXX.XX WWW 6
改成 arDdnsCheck XXXX.XX @ 6 后，运行就成功了

之前看使用说明比较简单，也不知道不需要更新子域名的话该咋整...

**Comment by errors4ever** [comment]
@yulelong 你好 我改成了
# IPv4:
arDdnsCheck "error-forever.com" www
# IPv6:
arDdnsCheck "error-forever.com" www  6
后,运行脚本出现如下信息,并且dnspod后台有更新记录
Fetching Host Ip
> Host Ip: xx.xxx.xx.xxx
> Record Type: A
Fetching Ids of www.error-forever.com
> Domain Ids: **************
Checking Record for www.error-forever.com
> Last Ip: xx.xxx.xx.xxx
> Last Ip is the same as host Ip
Fetching Host Ip
> Host Ip: 240e:388:1a52:2400:5a03:81ca:a031:b1d
> Record Type: AAAA
Fetching Ids of www.error-forever.com
> Domain Ids: 84595592 803465020
Checking Record for www.error-forever.com
> Last Ip: 240e:388:1a52:2400:5a03:81ca:a031:b1d
> Last Ip is the same as host Ip
