### ISSUE TITLE
只能取得IPv6的局域网地址怎么办？

### ISSUE THREAD

**Issue by once375ml** [rehiy/dnspod-shell#91]
中国移动，无IPv4公网地址，有IPv6的公网地址。

脚本可以成功运行，但是只能取到IPv6的局域网地址怎么办？类似于fe80……

**Comment by rehiy** [comment]
更新下脚本，fe80在新版是会过滤掉的

**Comment by once375ml** [comment]
这是刚下的shell，然后运行的结果：
Fetching Host Ip
> Host Ip: fec0:a2b2:4::b62
> Record Type: AAAA
Fetching Ids of ds218j.longinisle.life
> Domain Ids: 88802155 878852903
Checking Record for ds218j.longinisle.life
> Last Ip: arDdnsRecordIp - fe80::211:32ff:fe86:2aa6

**Comment by rehiy** [comment]
试试这个版本呢？https://github.com/rehiy/dnspod-shell/tree/844f841c4b7fb57077804b31e9e769b9e10b238c

**Comment by once375ml** [comment]
> 试试这个版本呢？https://github.com/rehiy/dnspod-shell/tree/844f841c4b7fb57077804b31e9e769b9e10b238c

Fetching Host Ip
> Host Ip: **### fec0**:a2b2:4::b62
> Record Type: AAAA
Fetching Ids of ds218j.longinisle.life
> Domain Ids: 88802155 878852903
Checking Record for ds218j.longinisle.life
> Last Ip: arDdnsRecordIp - fe80::211:32ff:fe86:2aa6


一样的结果。

  看了下 local lanIps="(^$)|(^::1$)|(^fe[8-9,A-F])"   这里应该抓不到 fec0 这样局域网IPv6吧？

**Comment by rehiy** [comment]
已更新添加小写正则

**Comment by once375ml** [comment]
> 已更新添加小写正则

成功，谢谢大神！

Fetching Host Ip
> Host Ip: 2409:8a55:3018:9e0:211:32ff:fe86:2aa6
> Record Type: AAAA
Fetching Ids of ds218j.longinisle.life
> Domain Ids: 88802155 878852903
Checking Record for ds218j.longinisle.life
> Last Ip: fe80::211:32ff:fe86:2aa6
Updating Record for ds218j.longinisle.life
> arDdnsUpdate - success

**Comment by jackadam1981** [comment]
Host Ip: fd33:fa30:4557::1
fd33 也没过滤

**Comment by jackadam1981** [comment]
local lanIps="(^$)|(^::1$)|(^[fF][eEdD][8-9a-fA-F])"
