### ISSUE TITLE
无法获取到ip

### ISSUE THREAD

**Issue by kfqkfy** [rehiy/dnspod-shell#97]
获取外网ip的地址ssl证书失效了，代码获取不到ip了
还有建议在sh脚本里面获取ip再作为参数传进去，刚自己改成3322的域名了，但有ddos防护，域过多的话一次性请求次数过多会被防住

**Comment by rehiy** [comment]
目前是优先从本地获取的，如果不需要ipv6，可以使用master分支代码。
